import './globals.css'
import { Headland_One } from 'next/font/google'
import NavBar from './components/NavBar'
import { EcommerceContextProvider } from './store/context'

const headland = Headland_One({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <EcommerceContextProvider>
        <body className={headland.className}>
          <NavBar/>
          {children}
        </body>
      </EcommerceContextProvider>
    </html>
  )
}
